name: TorinoTech-Action

on:
  push:
    branches:
      - master
      - dev/**
  pull_request:
    branches:
      - master

jobs:
  _githubbased_job:
    runs-on: ubuntu-latest
    env:
      DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: SETUP-Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: DBG-Executions
      if: env.DEBUG
      run: python -c "import sys; print(sys.executable)"
    - name: DBG-System
      if: env.DEBUG
      run: |
        pwd
        ls

  _dockerbased_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SETUP-Docker
      uses: ./docker/python3
