name: TorinoTech-Action

on:
  push:
    branches:
      - master
      - dev/**
  pull_request:
    branches:
      - master

jobs:
  _githubbased_job:
    name: GitHub based step
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: python -c "import sys; print(sys.executable)"
