name: TorinoTech-Action

on:
  push:
    branches:
      - master
      - dev/**
  pull_request:
    branches:
      - master

jobs:
  _githubbased_job:
    runs-on: ubuntu-latest
    steps:
    - name: Python action setyp
      uses: actions/checkout@v2
    - name:
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Executions
      run: |
        echo "WORKING PROGRESS"
        python -c "import sys; print(sys.executable)"
