name: TorinoTech-Action

on:
  push:
    branches:
      - master
      - dev/**
  pull_request:
    branches:
      - master

jobs:
  _githubbased_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python action setup
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Script executions
      run: |
        pwd
        ls
    - name: Script executions
      run: |
        echo "WORKING PROGRESS"
        python -c "import sys; print(sys.executable)"
